application: erpiv-loxal
version: a
runtime: go
api_version: go1

#builtins:
#- remote_api: on
#- datastore_admin: on

inbound_services:
- warmup

handlers:
# should precede ".*" (main URL handler)
- url: /static
  static_dir: static
# should precede ".*" (main URL handler)
- url: /favicon.ico
  static_files: static/theme/favicon.ico
  upload: static/theme/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /client/(.*)
  static_files: static/client/\1
  upload: static/client/.*
- url: /resource/(.*) # should be replaced by /my/(.*)
  static_files: static/resource/\1
  upload: static/resource/.*
- url: /my/(.*)
  static_files: static/resource/my/\1
  upload: static/resource/my/.*
- url: /module/(.*)
  static_files: static/module/\1
  upload: static/module/.*
- url: /cmd/.*
  script: _go_app
- url: /test/.*
  script: _go_app
- url: .*
  static_files: static/client/site/main.html
  upload: /static/client/.*

#- url: /static/module/CV/cache.mf
#  static_files: static/module/CV/cache.mf
#  upload: static/module/CV/cache.mf
#  mime_type: text/cache-manifest

#- url: /mystaticdir/(.*\.appcache)
#  static_files: mystaticdir/\1
#  mime_type: text/cache-manifest
#  upload: mystaticdir/(.*\.appcache)

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
